### ISSUE TITLE
Iago needs better connection exception handling

### ISSUE THREAD

**Issue by astrobokonon** [LowellObservatory/DataServants#15]
When the network to the site was down, Iago threw this exception:

```
2018-07-30 16:55:38,975 ERROR    Could not connect to host joe.lowell.edu, port 61613
Traceback (most recent call last):
  File "/Users/wadsworth/miniconda3/lib/python3.6/site-packages/stomp/transport.py", line 724, in attempt_connection
    self.socket = get_socket(host_and_port[0], host_and_port[1], self.__timeout)
  File "/Users/wadsworth/miniconda3/lib/python3.6/site-packages/stomp/backwardsock26.py", line 16, in get_socket
    return socket.create_connection((host, port), timeout)
  File "/Users/wadsworth/miniconda3/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/Users/wadsworth/miniconda3/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out
```
Then, when I tried to control-C it to kill it, I got the following:
```
2018-07-30 16:56:50,981 INFO     Got SIGINT; stopping...
2018-07-30 16:56:50,982 ERROR    Could not connect to host joe.lowell.edu, port 61613
Traceback (most recent call last):
  File "/Users/wadsworth/miniconda3/lib/python3.6/site-packages/stomp/transport.py", line 724, in attempt_connection
    self.socket = get_socket(host_and_port[0], host_and_port[1], self.__timeout)
  File "/Users/wadsworth/miniconda3/lib/python3.6/site-packages/stomp/backwardsock26.py", line 16, in get_socket
    return socket.create_connection((host, port), timeout)
  File "/Users/wadsworth/miniconda3/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/Users/wadsworth/miniconda3/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 22] Invalid argument
2018-07-30 16:57:02,964 INFO     Got SIGINT; stopping...
2018-07-30 16:57:02,964 ERROR    Could not connect to host joe.lowell.edu, port 61613
Traceback (most recent call last):
  File "/Users/wadsworth/miniconda3/lib/python3.6/site-packages/stomp/transport.py", line 724, in attempt_connection
    self.socket = get_socket(host_and_port[0], host_and_port[1], self.__timeout)
  File "/Users/wadsworth/miniconda3/lib/python3.6/site-packages/stomp/backwardsock26.py", line 16, in get_socket
    return socket.create_connection((host, port), timeout)
  File "/Users/wadsworth/miniconda3/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/Users/wadsworth/miniconda3/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 22] Invalid argument
2018-07-30 16:57:03,155 INFO     Got SIGINT; stopping...
2018-07-30 16:57:03,315 INFO     Got SIGINT; stopping...
2018-07-30 16:57:03,372 INFO     STOMP.py connection failed!
2018-07-30 16:57:03,372 INFO     PID 92336 is now out of here!
```

**Comment by astrobokonon** [comment]
Add to this ConnectionRefusedErrors; see also https://github.com/LowellObservatory/ligmos/issues/3 for similar work needed.

**Comment by astrobokonon** [comment]
This issue was moved to LowellObservatory/ligmos#4
