### ISSUE TITLE
Exception with ping NaNs

### ISSUE THREAD

**Issue by astrobokonon** [LowellObservatory/DataServants#17]
Saw this during a network fault of some kind 

```
2018-08-15 21:33:07,614 INFO     Instrument: HJ1
2018-08-15 21:33:10,614 INFO     Calling <function actionPing at 0x7f364d28b950>
2018-08-15 21:33:14,149 INFO     Done with action, 3.534664 since start
2018-08-15 21:33:14,150 INFO     6.535918 since outer loop start
2018-08-15 21:33:14,161 ERROR    Traceback (most recent call last):
2018-08-15 21:33:14,161 ERROR      File "Alfred.py", line 191, in <module>
2018-08-15 21:33:14,161 ERROR    alarmtime=alarmtime)
2018-08-15 21:33:14,161 ERROR      File "/home/lig/Codes/ligmos/ligmos/utils/common.py", line 566, in instLooper
2018-08-15 21:33:14,162 ERROR    ans, estop = instAction(each, outertime=startt)
2018-08-15 21:33:14,162 ERROR      File "/home/lig/Codes/ligmos/ligmos/utils/common.py", line 491, in instAction
2018-08-15 21:33:14,162 ERROR    **each.kwargs)
2018-08-15 21:33:14,162 ERROR      File "/home/lig/Codes/DataServants/dataservants/alfred/tasks.py", line 63, in actionPing
2018-08-15 21:33:14,162 ERROR    timeout=3)
2018-08-15 21:33:14,162 ERROR      File "/home/lig/Codes/ligmos/ligmos/utils/pingaling.py", line 66, in ping
2018-08-15 21:33:14,162 ERROR    ping = calcMedian(pres)
2018-08-15 21:33:14,163 ERROR      File "/home/lig/Codes/ligmos/ligmos/utils/pingaling.py", line 24, in calcMedian
2018-08-15 21:33:14,163 ERROR    if all(np.isnan(vals)):
2018-08-15 21:33:14,163 ERROR    TypeError
2018-08-15 21:33:14,163 ERROR    :
2018-08-15 21:33:14,163 ERROR    ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by astrobokonon** [comment]
Wasn't NaNs, but a change to the serviceping library returning datetime.timedelta objects. Fixed in https://github.com/LowellObservatory/ligmos/commit/87823381977717cebc20dfa7e16788b86fa119f3
