### ISSUE TITLE
Unhandled exception in Abu

### ISSUE THREAD

**Issue by astrobokonon** [LowellObservatory/DataServants#29]
I'm pretty sure this is related to a garbled or incomplete grab from the weather station? In any case, it causes a crash (but Abu restarts just fine).

```
2020-06-05 16:58:34,558 INFO     Starting a big sleep
2020-06-05 17:00:34,693 INFO     Connection still valid
2020-06-05 17:00:34,714 INFO     Good grab!
2020-06-05 17:00:34,715 ERROR    Traceback (most recent call last):
2020-06-05 17:00:34,715 ERROR      File "Abu.py", line 118, in <module>
2020-06-05 17:00:34,716 ERROR    main()
2020-06-05 17:00:34,716 ERROR      File "Abu.py", line 90, in main
2020-06-05 17:00:34,716 ERROR    bxml = abu.actions.columbiaTranslator(wxml)
2020-06-05 17:00:34,716 ERROR      File "/home/lig/Codes/DataServants/dataservants/abu/actions.py", line 30, in columbiaTranslator
2020-06-05 17:00:34,716 ERROR    pdict = xmld.parse(msg)
2020-06-05 17:00:34,716 ERROR      File "/opt/conda/lib/python3.7/site-packages/xmltodict.py", line 327, in parse
2020-06-05 17:00:34,717 ERROR    parser.Parse(xml_input, True)
2020-06-05 17:00:34,717 ERROR    xml.parsers.expat
2020-06-05 17:00:34,717 ERROR    .
2020-06-05 17:00:34,717 ERROR    ExpatError
2020-06-05 17:00:34,717 ERROR    :
2020-06-05 17:00:34,717 ERROR    not well-formed (invalid token): line 1, column 1936
```

**Comment by astrobokonon** [comment]
Hopefully closed by the changes up through 77eb3754b1868c46f4d4cdfdfb114257059be151 but testing now.  Might not be handling the None and {} stuff I added so things might cascade backwards a bit.

**Comment by astrobokonon** [comment]
I think I fixed it, but I set up an alert to see if/when Abu crashes next so I can notice it quicker and look at the log.  If I don't see it crash in the next week, I'll close this.

**Comment by astrobokonon** [comment]
It worked!  Closing.
