### ISSUE TITLE
Unhandled Alfred exception

### ISSUE THREAD

**Issue by astrobokonon** [LowellObservatory/DataServants#33]
Happend to catch this just now; corresponds with a planned network outage at the site and it looks like I have an alarm that is uncaught

```python
2021-04-08 17:12:08,328 INFO     Sleeping between instruments
2021-04-08 17:12:16,334 ERROR    Traceback (most recent call last):
2021-04-08 17:12:16,334 ERROR      File "Alfred.py", line 217, in <module>
2021-04-08 17:12:16,334 ERROR    main()
2021-04-08 17:12:16,334 ERROR      File "Alfred.py", line 191, in main
2021-04-08 17:12:16,335 ERROR    res = alfred.tasks.actionPing(pobj, db=db, debug=args.debug)
2021-04-08 17:12:16,335 ERROR      File "/home/lig/Codes/DataServants/dataservants/alfred/tasks.py", line 65, in actionPing
2021-04-08 17:12:16,335 ERROR    timeout=3)
2021-04-08 17:12:16,335 ERROR      File "/home/lig/Codes/ligmos/ligmos/utils/pingaling.py", line 69, in ping
2021-04-08 17:12:16,335 ERROR    time.sleep(waittime)
2021-04-08 17:12:16,335 ERROR      File "/home/lig/Codes/ligmos/ligmos/utils/multialarm.py", line 90, in __alarm_handler
2021-04-08 17:12:16,335 ERROR    func(*args, **keys)
2021-04-08 17:12:16,335 ERROR      File "/home/lig/Codes/ligmos/ligmos/utils/multialarm.py", line 55, in handle_timeout
2021-04-08 17:12:16,336 ERROR    raise TimeoutError(self.error_message, self.id_)
2021-04-08 17:12:16,336 ERROR    ligmos.utils.multialarm
2021-04-08 17:12:16,336 ERROR    .
2021-04-08 17:12:16,336 ERROR    TimeoutError
2021-04-08 17:12:16,336 ERROR    :
2021-04-08 17:12:16,336 ERROR    ('Timeout', 'Pings')
```

**Comment by astrobokonon** [comment]
Actually - I don't know why this wasn't caught.

```python
In [1]: import ligmos.utils.pingaling as pingy

In [2]: pingy.ping("localhost")
Out[2]: (0.287, 0, 0.75)

In [3]: pingy.ping("localhosty")
Out[3]: (-9999.0, 7, -9999.0)
```

**Comment by astrobokonon** [comment]
Ah - if I ping a nonexistent host, I get ScanFailed first:

```python
In [5]: pingy.ping("localhosty", timeout=3, debug=True)
Connection to host 'localhosty' failed!
DNS Lookup failed
Connection to host 'localhosty' failed!
DNS Lookup failed
Connection to host 'localhosty' failed!
DNS Lookup failed
Connection to host 'localhosty' failed!
DNS Lookup failed
Connection to host 'localhosty' failed!
DNS Lookup failed
Connection to host 'localhosty' failed!
DNS Lookup failed
Connection to host 'localhosty' failed!
DNS Lookup failed
Out[5]: (-9999.0, 7, -9999.0)
```
https://github.com/LowellObservatory/ligmos/blob/cfafc5604c04557e132d70766c2c3b1260fb004e/ligmos/utils/pingaling.py#L61-L67

**Comment by astrobokonon** [comment]
There we are - I am not catching the exception!  I think it's in the wrong indentation :-/

```python
In [6]: pingy.ping("tweedledum", timeout=3, debug=True)
Timed out: ('Timeout', 'Pings')
Timed out: ('Timeout', 'Pings')
Timed out: ('Timeout', 'Pings')
Timed out: ('Timeout', 'Pings')
{'host': 'tweedledum', 'port': 22, 'state': 'closed', 'durations': OrderedDict([('all', datetime.timedelta(seconds=3, microseconds=3106)), ('dns', datetime.timedelta(microseconds=2467)), ('connect', datetime.timedelta(seconds=3, microseconds=542))]), 'ssl_version': '', 'ip': '10.12.100.105'}
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
<ipython-input-6-de9e7231d9ab> in <module>
----> 1 pingy.ping("tweedledum", timeout=3, debug=True)

~/Codes/LIG/ligmos/ligmos/utils/pingaling.py in ping(host, port, repeats, waittime, timeout, median, debug)
     67                     print(str(err))
     68             nretries += 1
---> 69             time.sleep(waittime)
     70
     71     if median is True:

~/Codes/LIG/ligmos/ligmos/utils/multialarm.py in __alarm_handler(*zargs)
     88             # (tm, func, args, keys) = heapq.heappop(alarmlist)
     89             (_, func, args, keys) = heapq.heappop(alarmlist)
---> 90             func(*args, **keys)
     91             nextt = __next_alarm()
     92     finally:

~/Codes/LIG/ligmos/ligmos/utils/multialarm.py in handle_timeout(self)
     53
     54     def handle_timeout(self):
---> 55         raise TimeoutError(self.error_message, self.id_)
     56
     57     def __enter__(self):

TimeoutError: ('Timeout', 'Pings')
```

**Comment by astrobokonon** [comment]
Sure enough, this fixed it in the ipython test at least (https://github.com/LowellObservatory/ligmos/commit/d4849d13112df19852102739e4e9d42e7c01b908).

I think because the multialarm class overloads TimeoutError (https://github.com/LowellObservatory/ligmos/blob/d4849d13112df19852102739e4e9d42e7c01b908/ligmos/utils/multialarm.py#L41), it cascades downwards and I just need to catch the actual TimeoutError and not the specific one?  That's my best guess, but it made things work as expected:

```python
In [7]: pingy.ping("hostIKnowExistsInDNSButIsOffline", timeout=3, debug=True)
Timed out: ('Timeout', 'Pings')
Timed out: ('Timeout', 'Pings')
Timed out: ('Timeout', 'Pings')
Timed out: ('Timeout', 'Pings')
Timed out: ('Timeout', 'Pings')
Timed out: ('Timeout', 'Pings')
Timed out: ('Timeout', 'Pings')
Out[7]: (-9999.0, 7, -9999.0)
```

**Comment by astrobokonon** [comment]
Since this is a rare enough occurrence, I'll close this on the assumption that I've fixed it.  The next time we lose internet I'll check, or I'll check manually on a dev. machine that I can pull the plug on at will :)

**Comment by astrobokonon** [comment]
One final comment; looking at how I did things in the SSH library, the ping implementation may have just been wrong?  

```python
    def closeConnection(self, timeout=3):
        """
        """
        try:
            with multialarm.Timeout(id_="SSHClose", seconds=timeout):
                if self.ssh is not None:
                    self.ssh.close()
        except multialarm.TimeoutError as err:
            if err.id_ == "SSHClose":
                self.ssh = None
                print("SSH connection close failed? WTF?")
```

Note that the entire with() clause is wrapped in a try...except, and that's what is catching multialarm.TimeoutError.  Either way, I think this is just me not quite grasping the nuances of namespaces and overloads and all that jazz.  Oh well.

**Comment by astrobokonon** [comment]
Weirdly this just happened again this morning.  I'm not sure if I just haven't built the LDT library lately or what, or if I missed this elsewhere.

```python
2021-09-28 17:23:59,888 ERROR    Traceback (most recent call last):
2021-09-28 17:23:59,889 ERROR      File "/home/lig/Codes/DataServants/Alfred.py", line 217, in <module>
2021-09-28 17:23:59,889 ERROR    main()
2021-09-28 17:23:59,889 ERROR      File "/home/lig/Codes/DataServants/Alfred.py", line 191, in main
2021-09-28 17:23:59,889 ERROR    res = alfred.tasks.actionPing(pobj, db=db, debug=args.debug)
2021-09-28 17:23:59,889 ERROR      File "/home/lig/Codes/DataServants/dataservants/alfred/tasks.py", line 63, in actionPing
2021-09-28 17:23:59,889 ERROR    pings, drops, dnss = utils.pingaling.ping(iobj.host,
2021-09-28 17:23:59,889 ERROR      File "/home/lig/Codes/ligmos/ligmos/utils/pingaling.py", line 48, in ping
2021-09-28 17:23:59,890 ERROR    res = serviceping.scan(host, port=port, timeout=timeout)
2021-09-28 17:23:59,890 ERROR      File "/opt/conda/lib/python3.9/site-packages/serviceping/network.py", line 83, in scan
2021-09-28 17:23:59,890 ERROR    result_connection = network_socket.connect_ex((hostip, port))
2021-09-28 17:23:59,890 ERROR      File "/home/lig/Codes/ligmos/ligmos/utils/multialarm.py", line 90, in __alarm_handler
2021-09-28 17:23:59,890 ERROR    func(*args, **keys)
2021-09-28 17:23:59,890 ERROR      File "/home/lig/Codes/ligmos/ligmos/utils/multialarm.py", line 55, in handle_timeout
2021-09-28 17:23:59,890 ERROR    raise TimeoutError(self.error_message, self.id_)
2021-09-28 17:23:59,890 ERROR    ligmos.utils.multialarm
2021-09-28 17:23:59,890 ERROR    .
2021-09-28 17:23:59,890 ERROR    TimeoutError
2021-09-28 17:23:59,891 ERROR    :
2021-09-28 17:23:59,891 ERROR    ('Timeout', 'Pings')
```

**Comment by astrobokonon** [comment]
Happened again!  Damn.  Going to try to look at this now.

**Comment by astrobokonon** [comment]
Attempted fix in https://github.com/LowellObservatory/ligmos/commit/e9d459eabef2a8b9ef37a5d6f4ed8650e1dacb4b
