### ISSUE TITLE
Unhandled Iago exception

### ISSUE THREAD

**Issue by astrobokonon** [LowellObservatory/DataServants#35]
Broker was/is down, and I see this repeatedly in the logs:

```python
021-08-17 16:39:49,818 INFO     STOMP.py connection failed!
2021-08-17 16:39:49,818 INFO     Starting a big sleep
2021-08-17 16:40:01,842 INFO     No connection at all! Retrying...
2021-08-17 16:40:01,842 INFO     Connecting to 10.x.x.x
2021-08-17 16:40:04,777 ERROR    Could not connect to host 10.x.x.x, port 61613
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/stomp/transport.py", line 727, in attempt_connection
    self.socket = socket.create_connection(host_and_port, self.__timeout)
  File "/opt/conda/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/opt/conda/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host
```

**Comment by astrobokonon** [comment]
Likely related to https://github.com/LowellObservatory/ligmos/issues/4
